version: "3.8"

services:
  mongoservice:
    image: "mongo"
    restart: always
    container_name: "mongoservice"
    environment:
    - MONGO_INITDB_DATABASE=scraperdb
    # - MONGO_INITDB_ROOT_USERNAME=root
    # - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
    - 27018:27017

  scraperservice:
    build: .
    container_name: "scraperservice"
    ports:
    - "5001:5001"
    environment: 
    - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - "mongoservice"
    
  workerservice:
    image: "worker-service"
    container_name: "workerservice"
    ports:
    - "5000:5000"
    depends_on:
      - "scraperservice"